num = int(input('Digite qualquer numero para ver sua tabuada: '))
print('-' * 15)
print(f'{num} x {1} = {1*num}')
print(f'{num} x {2} = {2*num}')
print(f'{num} x {3} = {3*num}')
print(f'{num} x {4} = {4*num}')
print(f'{num} x {5} = {5*num}')
print(f'{num} x {6} = {6*num}')
print(f'{num} x {7} = {7*num}')
print(f'{num} x {8} = {8*num}')
print(f'{num} x {9} = {9*num}')
print(f'{num} x {10} = {10*num}')
print('-' * 15)
# Desafio 009 - Tabuada
