nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome..')
print('Seu nome tem {} letras'.format(len(nome)))
print('Seu primeiro nome é {}'.format(nome.split()[0]))
print('Seu último nome é {} '.format(nome.split()[-1]))
